# Generated by Django 5.1.1 on 2024-11-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='week_days',
            field=models.CharField(choices=[('mon_wed_fri', 'Dushanba/Chorshanba/Juma'), ('tue_thu_sat', 'Seshanba/Payshanba/Shanba')], default='mon_wed_fri', max_length=20),
        ),
    ]
