# Generated by Django 5.1.1 on 2024-12-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_attendance_options_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
