# Generated by Django 5.1.1 on 2024-12-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
