# Generated by Django 5.1.1 on 2024-12-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='users.group'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='users.student'),
        ),
        migrations.AlterField(
            model_name='dailypayment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_payments', to='users.group'),
        ),
        migrations.AlterField(
            model_name='dailypayment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_payments', to='users.student'),
        ),
    ]
