# Generated by Django 5.1.1 on 2024-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_attendance_group_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
