# Generated by Django 5.1.1 on 2024-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_date_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
