# Generated by Django 5.1.1 on 2024-12-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_student_date_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_group2', to='users.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_group', to='users.group'),
        ),
    ]
