# Generated by Django 5.1.1 on 2024-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_student_group2_alter_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group2',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_group', to='users.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='group2',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_group2', to='users.group'),
        ),
    ]
