# Generated by Django 5.1.1 on 2024-12-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_student_group2_remove_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of',
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.group'),
        ),
    ]
