# Generated by Django 5.1.1 on 2024-12-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_group_week_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='monthly_payment',
            new_name='monthly_fee',
        ),
    ]
